### ISSUE TITLE
pct:compile intermittently hangs when numThreads used

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/pct#293] opened 2018-03-14 20:44 UTC
### pct:compile intermittently hangs when numThreads used
Every now and then pct:compile hangs. The Jenkins console shows:

```
Started by upstream project "7.24/build work" build number 277
originally caused by:
 Started by an SCM change
[EnvInject] - Loading node environment variables.
Building on master in workspace d:\jenkins\workspace\7.24\build work
No emails were triggered.
[ui] $ cmd.exe /C "c:\jenkins\tools\hudson.tasks.Ant_AntInstallation\Ant\bin\ant.bat -file build.xml -Ddlc=oe11.6 build && exit %%ERRORLEVEL%%"
Unable to locate tools.jar. Expected to find it in C:\Program Files\Java\jre1.8.0_161\lib\tools.jar
Buildfile: d:\jenkins\workspace\7.24\build work\ui\build.xml

versions:
     [echo] Exact Financials version 7.24
     [echo] Apache Ant(TM) version 1.9.6 compiled on June 29 2015
[pct:version] PCT Version : pct-208-master-87b954be01663bf64f7b435edb02afdd6b4044fa
     [echo] OpenEdge Release 11.6.3.005  as of Mon Dec  5 06:36:50 EST 2016

compile:
    [mkdir] Created dir: d:\jenkins\workspace\7.24\build work\build\oe11.6\ui
[pct:compile] PCTCompile - Progress Code Compiler
```

### Your environment
* Operating system and version: Windows 2012 R2
* OpenEdge version: 11.6.3.005 x64
* Ant version: 1.96
* PCT version: 208

### Actual behaviour
See above. It seems that all threads are waiting for nothing.

I currently have a process hanging (for over a day :-)). I have used jcmd 4224 Thread.print to capture the following thread info:

```
4224:
2018-03-14 21:31:45
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.161-b12 mixed mode):

"Thread-6" #17 daemon prio=5 os_prio=0 tid=0x0000000017afd800 nid=0x11b8 in Object.wait() [0x00000000187bf000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.apache.tools.ant.taskdefs.StreamPumper.waitForInput(StreamPumper.java:246)
	- locked <0x00000000d6b7ea18> (a org.apache.tools.ant.taskdefs.StreamPumper)
	at org.apache.tools.ant.taskdefs.StreamPumper.run(StreamPumper.java:126)
	at java.lang.Thread.run(Unknown Source)

"Thread-5" #16 daemon prio=5 os_prio=0 tid=0x0000000017afc800 nid=0x12b0 in Object.wait() [0x00000000186be000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.apache.tools.ant.taskdefs.StreamPumper.waitForInput(StreamPumper.java:246)
	- locked <0x00000000d6b7e718> (a org.apache.tools.ant.taskdefs.StreamPumper)
	at org.apache.tools.ant.taskdefs.StreamPumper.run(StreamPumper.java:126)
	at java.lang.Thread.run(Unknown Source)

"Thread-4" #14 daemon prio=5 os_prio=0 tid=0x0000000017afe000 nid=0x154 in Object.wait() [0x00000000185bf000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.apache.tools.ant.taskdefs.StreamPumper.waitForInput(StreamPumper.java:246)
	- locked <0x00000000d6c1c9d8> (a org.apache.tools.ant.taskdefs.StreamPumper)
	at org.apache.tools.ant.taskdefs.StreamPumper.run(StreamPumper.java:126)
	at java.lang.Thread.run(Unknown Source)

"Thread-3" #13 daemon prio=5 os_prio=0 tid=0x0000000017af6800 nid=0xc58 in Object.wait() [0x00000000184bf000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.apache.tools.ant.taskdefs.StreamPumper.waitForInput(StreamPumper.java:246)
	- locked <0x00000000d6c1c6d8> (a org.apache.tools.ant.taskdefs.StreamPumper)
	at org.apache.tools.ant.taskdefs.StreamPumper.run(StreamPumper.java:126)
	at java.lang.Thread.run(Unknown Source)

"Thread-2" #12 prio=5 os_prio=0 tid=0x0000000017af2800 nid=0xf50 runnable [0x00000000183be000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ProcessImpl.waitForInterruptibly(Native Method)
	at java.lang.ProcessImpl.waitFor(Unknown Source)
	at org.apache.tools.ant.taskdefs.Execute.waitFor(Execute.java:534)
	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:463)
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:629)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:670)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:496)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Parallel$TaskRunnable.run(Parallel.java:454)
	at java.lang.Thread.run(Unknown Source)

"Thread-1" #11 prio=5 os_prio=0 tid=0x0000000017ae1800 nid=0xcf8 runnable [0x00000000182be000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ProcessImpl.waitForInterruptibly(Native Method)
	at java.lang.ProcessImpl.waitFor(Unknown Source)
	at org.apache.tools.ant.taskdefs.Execute.waitFor(Execute.java:534)
	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:463)
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:629)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:670)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:496)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Parallel$TaskRunnable.run(Parallel.java:454)
	at java.lang.Thread.run(Unknown Source)

"Service Thread" #9 daemon prio=9 os_prio=0 tid=0x00000000172c1800 nid=0xc0c runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #8 daemon prio=9 os_prio=2 tid=0x00000000159bd800 nid=0x1084 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #7 daemon prio=9 os_prio=2 tid=0x00000000159b9800 nid=0x530 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=2 tid=0x000000001595d800 nid=0x1354 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Attach Listener" #5 daemon prio=5 os_prio=2 tid=0x000000001595b000 nid=0xde8 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=2 tid=0x0000000000d0d800 nid=0x1064 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x000000001594a000 nid=0x1290 in Object.wait() [0x0000000016cdf000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000d5588ec0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	- locked <0x00000000d5588ec0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)

"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x0000000000d00000 nid=0x668 in Object.wait() [0x0000000016bdf000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000d5586b68> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Unknown Source)
	at java.lang.ref.Reference.tryHandlePending(Unknown Source)
	- locked <0x00000000d5586b68> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)

"main" #1 prio=5 os_prio=0 tid=0x0000000000c0e800 nid=0xd70 in Object.wait() [0x0000000000bfe000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000d6985b78> (a java.lang.Object)
	at java.lang.Object.wait(Unknown Source)
	at org.apache.tools.ant.taskdefs.Parallel.spinThreads(Parallel.java:355)
	- locked <0x00000000d6985b78> (a java.lang.Object)
	at org.apache.tools.ant.taskdefs.Parallel.execute(Parallel.java:210)
	at com.phenix.pct.PCTBgRun.execute(PCTBgRun.java:435)
	at com.phenix.pct.PCTBgCompile.execute(PCTBgCompile.java:133)
	at com.phenix.pct.CompilationWrapper.execute(CompilationWrapper.java:63)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:853)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)

"VM Thread" os_prio=2 tid=0x0000000015927800 nid=0xb38 runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x0000000000c27800 nid=0x1a8 runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x0000000000c29000 nid=0xddc runnable 

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x0000000000c2a800 nid=0x488 runnable 

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x0000000000c2d000 nid=0x1390 runnable 

"VM Periodic Task Thread" os_prio=2 tid=0x00000000172c4000 nid=0xae8 waiting on condition 

JNI global references: 44


```

### Expected behaviour
Just compile consistently... please.

### Steps to reproduce
The issue is intermittent. This compile target is defined as:

```
	<!-- compile sources -->

	<target name="compile">

		<mkdir dir="${build}/${ant.project.name}" />
		<pct:compile destDir="${build}/${ant.project.name}" displayFiles="1" stackSize="512" inputChars="32000" graphicalMode="true" debugListing="true" listing="true" xmlXref="true" keepXref="true" relativePaths="true" numThreads="2">
			<fileset dir="${src}" includes="**/*.p,**/*.cls" />
			<propath>
				<pathelement location="${src}/../i" />
				<pathelement location="${src}" />
			</propath>
		</pct:compile>

	</target>
```
If any other info can help - please let me know soon, I'm not sure how long I can keep this thread hanging.

**Comment by stefandrissen** [comment] 2018-03-14 20:52
The command line of pid 4224 is:

```
"java.exe" -classpath "c:\jenkins\tools\hudson.task.Ant_AntInstallation\Ant\lib\ant-launcher.jar" "-Dant.home=c:\jenkins\tools\hudson.tasks.Ant_AntInstallation\Ant" org.apache.tools.ant.launch.Launcher -file build.xml -Ddlc oe11.6 build
```
build is a target that depends on compile:

```
	<!-- build -->
	<target name="build" depends="versions,compile,pl" description="compile and create pl" />
```

**Comment by gquerret** [comment] 2018-03-14 20:54
Do you have any dead Progress process ? i.e. any procore / protrace in the base directory of the job or in temp dir ?  Or any Progress process still running in the base dir ?
Otherwise, just kill the processes.

**Comment by gquerret** [comment] 2018-03-14 20:58
It would be possible to add a timeout on the Java threads, so that builds wouldn't get stuck forever.
At least, that would solve the problems caused by Progress sessions crash.

**Comment by stefandrissen** [comment] 2018-03-14 20:59
Two "running" prowin.exe processes, both with the same command line:

```
c:\progress\oe11.6\bin\prowin.exe -b -q -inp 32000 -s 512 -p <temp>\pct_init21496.p
```
pct_init21496.p is pointing to:
```
ASSIGN PROPATH="C:\Users\SVCACC~~1\AppData\Local\Temp\pct54798.pl;" + PROPATH.
```

I know I can kill the processes / the job / reboot the server and the problem will go away **for a while.** The Jenkins server is currently in a relatively quiet state so that I can look at this issue.

**Comment by gquerret** [comment] 2018-03-14 21:02
How often does that happen ?
Could you execute a kill -USR1 on the process (or the Windows equivalent)

**Comment by stefandrissen** [comment] 2018-03-14 21:18
How often this occurs: a few times a month. 

I think your goal with kill -USR1 is to get a protrace? In that case proGetStack does the job (I think).

proGetStack 2620

```
=====================================================
PROGRESS stack trace as of Wed Mar 14 22:05:49 2018
=====================================================

Progress OpenEdge Release 11.6 build 1408 SP03 TF05 on WINNT 

Startup parameters:
-pf C:\progress\oe11.6\startup.pf,-cpinternal ISO8859-1,-cpstream ISO8859-1,-cpcoll Basic,-cpcase Basic,-d mdy,-numsep 44,-numdec 46,(end .pf),-b,-q,-inp 32000,-s 512,-p C:\Users\SVCACC~1\AppData\Local\Temp\pct_init21496.p


** ABL Stack Trace **

--> pct/_server.p at line 56  (pct/_server.r)
    C:\Users\SVCACC~1\AppData\Local\Temp\pct_init21496.p at line 25  (C:\Users\SVCACC~1\AppData\Local\Temp\pct_init21496.p)

** Persistent procedures/Classes **

** PROPATH **
C:\Users\SVCACC~1\AppData\Local\Temp\pct54798.pl,.,C:\progress\oe11.6\gui,C:\progress\oe11.6\gui\ablunit.pl,C:\progress\oe11.6\gui\adecomm.pl,C:\progress\oe11.6\gui\adecomp.pl,C:\progress\oe11.6\gui\adedesk.pl,C:\progress\oe11.6\gui\adedict.pl,C:\progress\oe11.6\gui\adeedit.pl,C:\progress\oe11.6\gui\adeicon.pl,C:\progress\oe11.6\gui\aderes.pl,C:\progress\oe11.6\gui\adeshar.pl,C:\progress\oe11.6\gui\adetran.pl,C:\progress\oe11.6\gui\adeuib.pl,C:\progress\oe11.6\gui\adeweb.pl,C:\progress\oe11.6\gui\adexml.pl,C:\progress\oe11.6\gui\dataadmin.pl,C:\progress\oe11.6\gui\OpenEdge.BusinessLogic.pl,C:\progress\oe11.6\gui\OpenEdge.Core.pl,C:\progress\oe11.6\gui\OpenEdge.ServerAdmin.pl,C:\progress\oe11.6\gui\prodict.pl,C:\progress\oe11.6\gui\protools.pl,C:\progress\oe11.6,C:\progress\oe11.6\bin

** Databases (logical/type/physical) **

** End of Protrace **
```
proGetStack 2960
```
=====================================================
PROGRESS stack trace as of Wed Mar 14 22:08:05 2018
=====================================================

Progress OpenEdge Release 11.6 build 1408 SP03 TF05 on WINNT 

Startup parameters:
-pf C:\progress\oe11.6\startup.pf,-cpinternal ISO8859-1,-cpstream ISO8859-1,-cpcoll Basic,-cpcase Basic,-d mdy,-numsep 44,-numdec 46,(end .pf),-b,-q,-inp 32000,-s 512,-p C:\Users\SVCACC~1\AppData\Local\Temp\pct_init21496.p


** ABL Stack Trace **

--> pct/_server.p at line 56  (pct/_server.r)
    C:\Users\SVCACC~1\AppData\Local\Temp\pct_init21496.p at line 25  (C:\Users\SVCACC~1\AppData\Local\Temp\pct_init21496.p)

** Persistent procedures/Classes **

** PROPATH **
C:\Users\SVCACC~1\AppData\Local\Temp\pct54798.pl,.,C:\progress\oe11.6\gui,C:\progress\oe11.6\gui\ablunit.pl,C:\progress\oe11.6\gui\adecomm.pl,C:\progress\oe11.6\gui\adecomp.pl,C:\progress\oe11.6\gui\adedesk.pl,C:\progress\oe11.6\gui\adedict.pl,C:\progress\oe11.6\gui\adeedit.pl,C:\progress\oe11.6\gui\adeicon.pl,C:\progress\oe11.6\gui\aderes.pl,C:\progress\oe11.6\gui\adeshar.pl,C:\progress\oe11.6\gui\adetran.pl,C:\progress\oe11.6\gui\adeuib.pl,C:\progress\oe11.6\gui\adeweb.pl,C:\progress\oe11.6\gui\adexml.pl,C:\progress\oe11.6\gui\dataadmin.pl,C:\progress\oe11.6\gui\OpenEdge.BusinessLogic.pl,C:\progress\oe11.6\gui\OpenEdge.Core.pl,C:\progress\oe11.6\gui\OpenEdge.ServerAdmin.pl,C:\progress\oe11.6\gui\prodict.pl,C:\progress\oe11.6\gui\protools.pl,C:\progress\oe11.6,C:\progress\oe11.6\bin

** Databases (logical/type/physical) **

** End of Protrace **
```

[pct_server.p](https://github.com/Riverside-Software/pct/blob/master/src/progress/pct/_server.p):
```
/* Now that we have connected, loop forever listening for data from the server.
 * When we receive data, pass it to the read handler and then start looping again. */
EternalLoop:
DO WHILE aOk:
    IF VALID-HANDLE(hSocket) THEN DO:
        WAIT-FOR READ-RESPONSE OF hSocket. // line 56
    END.
END.
RETURN '0'.
```

So it seems Progress is waiting for information from Java?

Which /may/ shed some light on the issue - since I /think/ that in this case there is actually nothing new to compile.

**Comment by gquerret** [comment] 2018-03-14 21:23
No interesting message in the build log ?

**Comment by stefandrissen** [comment] 2018-03-14 21:24
Which build log? The complete Jenkins console output was posted in the initial issue.

**Comment by gquerret** [comment] 2018-03-14 21:27
Didn't see it !

**Comment by stefandrissen** [comment] 2018-03-14 21:30
The only part I didn't include in the console output is the spinner on the last line indicating that Jenkins is happy waiting too.

**Comment by maelstraggiotti** [comment] 2018-03-15 08:09
I know it doesn't help much but we encounter a similar issue, under TeamCity. I'll try to fetch more info next time it occurs.

**Comment by stefandrissen** [comment] 2018-03-15 08:12
Well it helps keep me out of my padded cell :-)

**Comment by gquerret** [comment] 2018-03-22 11:36
In `WAIT-FOR READ-RESPONSE PAUSE xx`, is it possible to know if timeout occured ?

**Comment by stefandrissen** [comment] 2018-03-22 20:57
Yes, by keeping track of time elapsed yourself: https://knowledgebase.progress.com/articles/Article/P59184

**Comment by gquerret** [comment] 2018-03-23 08:26
Introduced a timeout in the OE code. Can you try [this version](https://dl.rssw.eu/PCT.jar) ?

**Comment by stefandrissen** [comment] 2018-03-23 09:12
I've updated our environment.

**Comment by gquerret** [comment] 2018-04-04 19:29
@stefandrissen Did you find any problem with this version ?

**Comment by stefandrissen** [comment] 2018-04-04 21:02
I’ve had no problems since switching to 209 pre - but since the problems were intermittent this may not be saying much.

**Comment by gquerret** [comment] 2018-07-09 13:53
Did you get better results with this version ?

**Comment by stefandrissen** [comment] 2018-07-09 14:12
I have not encountered this issue since switching to 209 pre.

**Comment by gquerret** [comment] 2018-07-09 14:22
Merged in master

**Closed as completed by gquerret** 2018-07-09 14:22 UTC
