### ISSUE TITLE
Insufficient disk space does not fail build

### ISSUE THREAD

**Issue by hutcj** [Riverside-Software/pct#412] opened 2020-03-31 12:01 UTC
### PCT build via Jenkins 
The PCTCompile task allows build failure as success.

### Your environment
* AIX 7.1
* OpenEdge 11.7.5
* Ant 1.9.8
* PCT 213

### Actual behaviour
PCT cannot compile all files due to lack of disk space. However, it continues the build as if the compile was successful.
```
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] TERM env variable is not set. Assuming an ANSI terminal. (4032)
[PCTCompile] TERM env variable is not set. Assuming an ANSI terminal. (4032)
[PCTCompile] TERM env variable is not set. Assuming an ANSI terminal. (4032)
[PCTCompile] TERM env variable is not set. Assuming an ANSI terminal. (4032)
[PCTCompile] Insufficient disk space or Write access denied. (291)
[PCTCompile] Insufficient disk space or Write access denied. (291)
[PCTCompile] Insufficient disk space or Write access denied. (291)
[PCTCompile] Result: 2
[PCTCompile] Result: 2
[PCTCompile] Result: 2
[PCTCompile] Insufficient disk space or Write access denied. (291)
[PCTCompile] Insufficient disk space or Write access denied. (291)
[PCTCompile] Result: 2
[PCTCompile] 700 file(s) compiled
...
BUILD SUCCESSFUL
Total time: 3 minutes 36 seconds
```

### Expected behaviour
Build should fail if compiler cannot generate rcode due to disk usage.

### Steps to reproduce
Use PCTCompile on a filesystem with lower disk space available than required.

**Comment by gquerret** [comment] 2020-03-31 14:25
Reproduced, only happens with multi-threaded build, error seems to be swallowed.

**Comment by gquerret** [comment] 2020-04-01 05:56
If the `COMPILE` statement runs out of disk space, then it is trapped by the AVM. But if any of the attributes (such as `XREF` or `LISTING`) is used, then it crashes the AVM (at least with 11.7.5 on Windows). 
The real problem is then that the Java process doesn't handle this case correctly. Losing connection with an AVM should be considered a failure.

**Comment by gquerret** [comment] 2020-04-06 06:35
Fixed in master

**Closed as completed by gquerret** 2020-04-06 06:35 UTC
