### ISSUE TITLE
"included" files are generating with include file names truncated

### ISSUE THREAD

**Issue by wilddoug** [Riverside-Software/pct#120] opened 2015-11-18 22:40 UTC
Attached are two files which show the issue.  In server/oe/t-oeet.w, we have many includes.  One is server/oe/m-oee/lnval.i which contains an include server/oe/t-oee-lnval.i.

The resulting t-oeet.w.xref looks perfect when referring to the first include.
gui-code\server\oe\t-oeet.w gui-code\server\oe\t-oeet.w 136 INCLUDE server/oe/m-oee-lnval.i
Also, when refering to the included include everything looks good:
gui-code\server\oe\t-oeet.w gui-code\server\oe\m-oee-lnval.i 2120 INCLUDE server/oe/t-oee-lnval.i

However, the problem is in the t-oeet.w.inc file -- the file names of some of the includes are truncated:
"erver\oe\t-oee-lnval.i" ?
( should read:  "server\oe\t-oee\lnval.i" "gui-code\server\oe\t-oee-lnval.i" )

Most do show correctly in the .inc file:
"cores-implied-fields.i" "gui-code\trend\cores-implied-fields.i"

This was tested in Progress 11.6 32-bit, PCT 199, ANT 194 on Windows 2008R2

[t-oeet.w.xref.txt](https://github.com/jakejustus/pct/files/38407/t-oeet.w.xref.txt)
[t-oeet.w.inc.txt](https://github.com/jakejustus/pct/files/38408/t-oeet.w.inc.txt)

**Comment by jakejustus** [comment] 2015-11-19 08:41
More than probably related to https://github.com/jakejustus/pct/issues/47
As a temp workaround, you can use xmlXref="true" in your PCTCompile. That will probably slow down the build (I don't have metrics), but result will be correct.

**Comment by jakejustus** [comment] 2015-11-20 14:52
Were you able to verify if the problem is solved with xmlXref ?
I had another look and was able to reproduce the problem, but I'm really unsure I'll provide a fix for the non-xml version of xref, as it will require a significant amount of code to solve a problem in the import statement. However, if you want to have a look, you can use test35 in PCTCompile, and see the offending code in src/progress/v11/pctCompile.p (procedure importxref).

Gilles

**Comment by wilddoug** [comment] 2015-11-20 18:15
There is also a bug in the xmlXref version of the inc files as well.
Attached are the two files generated from the same code.
You'll notice that many includes now have linefeeds included as part of the filename.
And the xmlXref seems significantly slower, but I do not have any hard data on that.

[t-oeet.w.xref.txt](https://github.com/jakejustus/pct/files/40371/t-oeet.w.xref.txt)
[t-oeet.w.inc.txt](https://github.com/jakejustus/pct/files/40372/t-oeet.w.inc.txt)

**Comment by jakejustus** [comment] 2015-11-21 09:43
Problem fixed for the linefeeds, that was the case when the include name was immediately followed by a newline, and then spaces.

**Comment by jakejustus** [comment] 2015-11-21 09:50
See https://github.com/jakejustus/pct/commit/c8854a67e2634e1f32a6dca6fb414c725444419f

**Comment by jakejustus** [comment] 2015-11-22 20:23
In case you'd like to test this version, you can download it here : http://pugfr.riverside-software.fr/PCT.jar

**Comment by jakejustus** [comment] 2015-11-25 20:59
Were you able to try this version?

**Comment by wilddoug** [comment] 2015-12-02 20:00
I'm very sorry - I haven't had a chance yet.  I'll attempt a test in the next day or two.  Thanks!!

**Comment by wilddoug** [comment] 2015-12-02 21:17
That did fix the issue when using the xmlXref="true" option in PCTCompile.  It is still broken when not using the xmlXref, but I'll keep an eye on the build times.  if they are ok, we'll stay in xmlXref mode.  thanks!!

**Comment by jakejustus** [comment] 2015-12-03 09:58
Thanks for your report ! As it's very unlikely I'll take time to fix the standard XREF issue, I'll close the issue.

**Closed as completed by jakejustus** 2015-12-03 09:58 UTC
Labels: bug, Priority-Low
