### ISSUE TITLE
PCTRun with nested element propath

### ISSUE THREAD

**Issue by Hanna19** [Riverside-Software/pct#248] opened 2017-06-06 13:12 UTC
Hi,
I use within PCTRun the nested element propath with the refid:
```
<propath refid="dp-propath"/>
```
Because our directory structure is huge, the dp-propath.xml contains 486 entries. 
PCTRun gives me error :
```
[PCTRun] REPLACE/CONCAT may not result in data > 32000 bytes. (11678)
```
It works if I remove some entries. I also noticed that the amount of pathelement entries which are processed differs between servers (always Linux).  
Looking for your advice,
Hanna

**Comment by spazzymoto** [comment] 2017-06-07 08:10
Hi Hanna,

I am not able to reproduce this on my side and am not entirely sure this error is coming from the propath. What happens if you just return '0' from the .p you are running, if that runs fine then i don't think the issue is on PCT's side. 

I have included the test i used, if you can change this to fail i can use it on my side to debug for you.
[test.zip](https://github.com/Riverside-Software/pct/files/1057275/test.zip)

**Comment by spazzymoto** [comment] 2017-06-07 08:42
Ah i managed to reproduce it, i will take a look

**Comment by spazzymoto** [comment] 2017-06-07 09:50
Hi Hanna,
Are the pathelements length different on each server? If you could make the length of the path elements as short as possible that would probably help as i think you are blowing the character limit for a character.

ie:
`<pathelement location="/test/propath/dir1" />`
instead of
`<pathelement location="/home/user/Projects/test/propath/dir1" />`

It seems setting the propath using the PROPATH environment variable could also get you around the issue. Not sure how practical that is for you?

I have tested a change in pct to pass the PROPATH to process using the environment variable but would need to run this past @gquerret first

**Comment by stefandrissen** [comment] 2017-06-07 22:00
486 entries!?!? 

Within the AVM the propath is a pseudo-character with a 32000 byte limit-
 http://knowledgebase.progress.com/articles/Article/P181369

So look what happens when you assign a longchar to the propath:

```
def var lcc as longchar.
lcc = "hello".
propath = lcc.
message entry( 1, lcc ) view-as alert-box.
````

While it is possible to set the PROPATH environment variable with a longer value on Linux - I wonder if it actually works correctly - I created a .sh with a total length of 87000 characters and the AVM reports the length of the propath as 21847 - which taking into account the auto-added entries is pretty close to 87000 - 32768 - 32768 - ie an overflowed integer.

On the other hand message entry( 1, propath ) and message entry( 1000, propath ) are returning the correct values - so it may work.

**Comment by gquerret** [comment] 2017-06-07 23:18
486 entries... That's insane !
How do you compile and execute your application (before using PCT) ? I assume that you have exactly the same problem ? As Stefan said, PROPATH is limited to 32k, so there's nothing I can do on my side.
You can try using relative paths, shorter path names (if using absolute paths), or reduce the number of entries.

**Comment by stefandrissen** [comment] 2017-06-08 07:43
@gquerret - it's not /really/ a character - it's a pseudo character - when the PROPATH is set by environment variable then a path longer than 32k does work as my last comment illustrates. My path was 87k with 1000 entries set by an 

````
export PROPATH=reallylong
pro
````

The AVM was able to correctly pick up entry 1 and entry 1000 of the path.

**Comment by spazzymoto** [comment] 2017-06-08 08:22
I can create a pull request for the change i made to test this as well if you like @gquerret

**Comment by gquerret** [comment] 2017-06-08 13:21
@stefandrissen My bad, I didn't read the link you provided (was at the airport, and quickly added this comment).
So this would work with the PROPATH env variable. However, I'm not really keen on introducing such a huge change for a very specific and uncommon use case. The way propath is set didn't change in years, and works. And on top of that, from the KB entry, the PROPATH variable is not used on Windows.

**Comment by gquerret** [comment] 2017-06-08 13:23
@spazzymoto You can open the pull request, it's just that I think it's unlikely to be merged right now!

**Comment by gquerret** [comment] 2017-06-14 15:59
No news, closing issue

**Closed as completed by gquerret** 2017-06-14 15:59 UTC
