### ISSUE TITLE
pct:compile corrupt inc files preventing automatic recompile

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/pct#191] opened 2016-12-02 23:21 UTC
Apache Ant(TM) version 1.8.4 compiled on May 22 2012
    PCT Version : jenkins-QA-PCT-198
    OpenEdge Release 11.6 as of Fri Oct 16 19:02:26 EDT 2015

We have some extensive include usage in our application. A change in one of the includes was not resulting in a recompile of all users of this include. Further inspection shows that multiple pct inc files are corrupt:

```
"2\2\work\bl\finance\ifallgen\gatrss-bank.p" ?
"2\2\work\bl\finance\ifallinc\atrs-fields\acc_nr.i" ?
<snip>
"72\2\work\i\ifall\general\gendefs.i" ?
"72\2\work\i\system\ifallinc\ifstexob.i" ?
"assets/ids/fas_ast.only.i" "C:\tfs\ef72\2\work\bl\assets\ids\fas_ast.only.i"
...

```
A similar correct file starts with:

```
"finance/ids/atrsh.i" "C:\tfs\ef72\2\work\bl\finance\ids\atrsh.i"
"finance/ids/atrss.i" "C:\tfs\ef72\2\work\bl\finance\ids\atrss.i"
...
```
A clean build only helps once - the inc files are corrupt again preventing a future incremental build from picking up all changes.

A snippet of the build.xml:

```
<pct:compile 
  destDir="${build}/${ant.project.name}/progress"
  verbose="false" 
  stackSize="512" 
  inputChars="32000" 
  debugListing="true" 
  listing="false" 
  keepXref="false" 
  xmlXref="false"
>
  <pct:db_connection dbName="exactcs" dbDir="${build}/db/progress" singleUser="true">
    <alias name="exactcssh" />
  </pct:db_connection>
  <fileset dir="${src}/bl" includes="**/*.p" />
  <propath>
    <pathelement location="${src}/i" />
    <pathelement location="${src}/bl" />
  </propath>
</pct:compile>
```

Based on the comments in pct/compile.p in importxref (line 621) - the xref for these files does contain lines longer than 2000 characters.

**Comment by stefandrissen** [comment] 2016-12-03 00:05
Here are four lines from the xref file:
[gatrss-bank.p.xref.txt](https://github.com/Riverside-Software/pct/files/628560/gatrss-bank.p.xref.txt)

The normal IMPORT in ImportXref (**without** the 2000 character fix attempt) works fine (11.6 and 10.1C).

On further searching, this is the same issue as #120 which was also reporting that the fix for #47 was bad.

The xmlxref option does not have this issue.

**Comment by gquerret** [comment] 2016-12-03 07:33
Isn't xmlXref a viable solution ?

**Comment by stefandrissen** [comment] 2016-12-03 14:18
It may be, I need to check metrics and will get back on that. The simple fix for importXref is to replace the black magic stream synchronize with:

    seek stream sxref to seek( sxref2 ).

Additionally, _if_ importXref cannot be made to work correctly it should be removed entirely, since silently breaking build processes is a critical bug.

Metrics (mm:ss) on the main bulk of our code base which includes creating databases and putting r-code in pls::

    pc   xmlxref xref
    one: 13:50   08:07
    one: 13:31   07:48 (compile only)
    two: 23:16   11:53
    two: 19:37   11:23 (compile only)
    

pc one is my games pc with 4GHz CPU, 16GB RAM & most importantly an SSD, pc two is a business pc with 3.4GHz, 8GB RAM and a rotating rust drive.

**Comment by NickHeap** [comment] 2016-12-03 19:26
Hi I think this is the problem that we ran into with huge files.
It was happening under 11.4 with std xrefs.
The fix was to comment this bit out in compile.p
    /* GC Bug #47 - Lines longer than 2000 characters are truncated. This IMPORT is there to synchronize both streams. */
    IF LENGTH (cTmp) >= 2000 THEN
      IMPORT STREAM sXREF UNFORMATTED cTmp2.

**Comment by gquerret** [comment] 2016-12-04 20:10
I'll have to dig in history before doing a revert on this specific commit, as there was a reproducible test case and a fix. Things may have changed in recent releases, so a conditional switch may be required. 

@stefandrissen Could you find the time of the PCTCompile part only ?
And still using rotating rust drive on a business PC ? Unlucky you :-(

**Comment by stefandrissen** [comment] 2016-12-04 21:45
To verify if the 'seek stream to seek' fix would work I'm trying to reproduce the issue from #47 - but am failing. 

I have:
- Progress OpenEdge 11.6x64
- test.p from that issue.
- created a deep user directory structure identical to what is found in the xref of that issue
- pct-198.jar with modified pct-src.zip in which pct/v11/pctCompile.p has the fix lines commented out 
- am starting ant with -DPCT-SRC=true

Error 141 is not appearing in my crc file but simply:

    "sports.Item" "40569"

I will have a quick sanity check with an older progress version - please find my build files attached.

[test47.zip](https://github.com/Riverside-Software/pct/files/629848/test47.zip)

Update 1: Tested with 11.2.1 (32-bit) - issue 47 is not reproducible.
Update 2: added times for pc one compile only a few posts up

**Comment by gquerret** [comment] 2016-12-05 05:44
Test case associated with issue #47 was PCTCompileTest#test35(), which runs exactly the same way with and without this `IF LENGTH (cTmp) >= 2000` line (on 10.2B 64 bits and 11.6, both on Linux)
An additional test case is PCTCompileTest#test42(), which was incorrectly written (had a comment saying that 11.3 was broken), and which works correctly without the specified line.

**Comment by gquerret** [comment] 2016-12-05 05:57
Branch and pull request created, this will be tested on different version and platforms. Will try to get access to a 11.3 instance, I'm pretty sure the issue appeared when 11.3 was the current release.

**Comment by stefandrissen** [comment] 2016-12-05 08:07
Great! Unfortunately we do not have an 11.3 add-on license, or I would have been able to try it out myself.

If the case is reproducible with 11.3, you could make the fix proversion specific and optionally try 

seek stream sxref to seek( sxref2 )

**Comment by gquerret** [comment] 2016-12-05 19:46
Sorry, had to leave work this morning, probably until Wednesday, will have a look then.

**Comment by gquerret** [comment] 2016-12-08 14:42
Dug into my mailbox, and found how to reproduce the initial issue ; this piece of code shows the invalid behavior of the import statement with lines longer than 2000 characters :
```
define temp-table tt no-undo
 field tt1 as char
 field tt2 as char
 field tt3 as char
 field tt4 as char
 field tt5 as char.

output to 'file.txt'.
put unformatted 'field1 field2 field3 field4 field5 ' fill('0123456789', 200) skip.
put unformatted 'field1 field2 field3 field4 field5' skip.
output close.

input from 'file.txt'.
repeat:
 create tt.
 import tt.
end.

for each tt:
  disp tt1 length(tt5).
end.
```

Versions 11.x (where x >= 3) see three records when there are only two.The fact I'm not able to reproduce the issue may just mean that XREF output changed a bit, as the only impacted line is the one immediately after the long line.
I'll however have a look at your `seek stream sxref to seek( sxref2 )` solution.

**Comment by stefandrissen** [comment] 2016-12-08 20:55
Thanks for the reproducible, I just went thru time and can confirm the same issue (second tt record has last part of first line of file) on (all Windows):

- 9.1E
- 10.1.C
- 10.2B (32-bit)
- 11.2 (32-bit)
- 11.6 (64-bit) 

And the issue is actually that there is data for more fields in the file than there are temp-table fields (tt has 5 fields, file has data for 6). 

A very cheap trick can be to add a soak field to the temp-table:

    field csoak as character extent 100

In which 100 is probably overkill, the current pct ttxref defines 5 fields:

    DEFINE TEMP-TABLE ttXref NO-UNDO
      FIELD xProcName   AS CHARACTER
      FIELD xFileName   AS CHARACTER
      FIELD xLineNumber AS CHARACTER
      FIELD xRefType    AS CHARACTER
      FIELD xObjID      AS CHARACTER FORMAT "X(50)"

If I I look at the [help file](https://documentation.progress.com/output/ua/OpenEdge_latest/index.html#page/dvref/compile-statement.html#ww3_7_199_3_4_7_22_4_12_3) on compile xref it would seem a few more overflow fields is sufficient - if I look at the [xref parser](http://www.oehive.org/node/754) on oehive it is circumventing the issue by only importing unformatted into a character variable and then pulling that apart.

Did anyone log an issue at Progress for this?

On the other hand, you could argue that the [help file](https://documentation.progress.com/output/ua/OpenEdge_latest/index.html#page/dvref/import-statement.html) on the import statement is warning you about this:

"If you do not use the UNFORMATTED option, the data in the input stream **must be in a standard format** to be read back into ABL."

Alternatively since ttxref only contains five fields:

      import ttXref.xProcName ttXref.xFileName ttXref.xLineNumber ttXref.xRefType ttXref.xObjID ^ ^ ^ ^ ^ ^ ^ ^ ^ ^.

**Comment by gquerret** [comment] 2016-12-09 08:20
Git branch Issue191 contains your fix : 
https://github.com/Riverside-Software/pct/blob/Issue191/src/progress/pct/compile.p#L620
You can see how the ttXref is filled, a mix of `import ttXref` and a substring of the full line (the last field xObjId can contain an unlimited number of spaces and is not double quoted.

Test cases were updated, seems to work perfectly.

**Comment by gquerret** [comment] 2016-12-09 08:20
@stefandrissen Could you build this branch (I assume you know how to do it), and test on your codebase ?

**Comment by stefandrissen** [comment] 2016-12-09 09:38
@gquerret I have not built pct before, so had a quick attempt:
- downloaded latest ant version (1.9.7)
- downloaded latest jdk (1.8u112)
- downloaded pct branch 191
- built pct branch 191
- removed pct:compile verbose attribute from my build.xml (build #206) 

But then: pct:compile doesn't support the nested "db_connection" element.

I'm not sure if this is a result of my build or something else.

    <pct:compile destDir="${build}/${ant.project.name}/progress" stackSize="512" inputChars="32000" debugListing="${pct.compile.debuglisting}" listing="${pct.compile.listing}" xmlXref="${pct.compile.xref.xml}" keepXref="${pct.compile.xref.keep}">
    	<pct:db_connection dbName="exactcs" dbDir="${build}/db/progress" singleUser="true">
    		<alias name="exactcssh" />
    	</pct:db_connection>
    	<pct:db_connection dbName="edis" dbDir="${build}/db/progress" singleUser="true">
    		<alias name="edissh" />
    	</pct:db_connection>
    	<pct:db_connection dbName="synergysh" dbDir="${build}/db/progress" singleUser="true" />
    	<fileset dir="${src}/bl" includes="**/*.p" />
    	<propath>
    		<pathelement location="${src}/i" />
    		<pathelement location="${src}/bl" />
    	</propath>
    </pct:compile>`

**Comment by gquerret** [comment] 2016-12-09 12:22
Unwanted side effect of the PCTCompile and PCTCompileExt merge :-(
Could you do a global search and replace from `pct:db_connection` to `pct:dbConnection` ?

**Comment by stefandrissen** [comment] 2016-12-09 13:36
Thanks, that helps.

Issue resolved. Regular xref behaving again.

Are you planning on releasing build 207 any time soon? For now I've named my local build pct-207-alpha.jar.

I like output of displayFiles="1" :-)

Kind regards,

Stefan

**Comment by gquerret** [comment] 2016-12-09 13:42
207 will be released soon, but I don't know when exactly. Thanks for your report !

**Closed as completed by gquerret** 2016-12-09 13:42 UTC
