### ISSUE TITLE
Invalid 'buffer' parameter used in WRITE method

### ISSUE THREAD

**Issue by alexwiese** [Riverside-Software/pct#443] opened 2021-02-16 01:24 UTC
**Describe the bug**

When there is a compilation warning and then a compilation error the Progress application compiler gives the correct error and warning messages, however PCT does not.

From Progress application compiler:
```
Compiling C:\git\pulse-staging\Explorer\src\servers\test-file.p
** WARNING--TRANSACTION keyword given within actual transaction level. (214)
** Field abc does not exist in table _File. (442)
** C:\git\pulse-staging\Explorer\src\servers\test-file.p Could not understand line 18. (196)
```

Using PCT the following message is displayed, but the script continues without error, causing our build process to report success incorrectly.
```
Invalid 'buffer' parameter used in WRITE method
```

If I fix the issue that causes the **WARNING** then PCT reports the error and fails correctly, so the warning appears to be what causes the issue.

```
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] Error compiling file 'C:/git/pulse-staging/Explorer/src/servers/test-file.p' ...
[PCTCompile]  ... in main file at line 18 column 5
[PCTCompile]      FOR EACH _File FIELDS (abc) NO-LOCK:
[PCTCompile] -----^
[PCTCompile] ** Field abc does not exist in table _File. (442)
[PCTCompile]
[PCTCompile] 0 file(s) compiled
[PCTCompile] Failed to compile 1 file(s)
```

**To Reproduce**

Here is the minimal reproduction:

```
DEF TEMP-TABLE tt-test
    FIELD id AS CHAR.

PROCEDURE A:

    FOR EACH tt-test:
        DO TRANSACTION: 
            DO TRANSACTION: 
                DISPLAY id.
            END.
        END. 
    END.

END PROCEDURE.

PROCEDURE B:

    FOR EACH _File FIELDS (abc) NO-LOCK:
        DISPLAY "Test".
    END.    

END PROCEDURE.
```

**Expected behavior**
I expect the PCT tools to report the compilation error and for the build to fail, not silently succeed.

**Environment**
- Windows 10 - 1909
- OpenEdge 11.7.5
- Ant 1.9.7
- [PCTVersion] PCT Version : pct-217-master-76991b4f4ca4e07b8f0e75695d783ca43cbe204c

**Additional context**

**Comment by gquerret** [comment] 2021-02-16 07:09
Do you use any callback ? This line seems weird:
```
Invalid 'buffer' parameter used in WRITE method
```
No 11.7.5 available on the computer I'm currently using, just 12.2, but I can't reproduce the issue.

**Comment by alexwiese** [comment] 2021-02-17 23:14
@gquerret not using any callback.

```
		<echo message="Compiling procedures..."/>
		<PCTCompile destDir="${explorer.build.dir}\src" 
			stackSize="256" graphicalMode="true" numThreads="8" tempDir="${temp.dir}"> 					
			<PCTConnection dbName="${db.name}" logicalName="plswms" dbDir="${db.dir}" singleUser="${db.offline}" readOnly="true"/>

			<fileset dir="${explorer.src.dir}\src">
				<include name="**\*.p"/>
				<include name="**\*.w"/>
				<exclude name="support\**"/>
			</fileset>

			<propath>
				<pathelement location="${explorer.src.dir}"/>
				<pathelement location="${explorer.src.dir}\trig"/>
				<pathelement location="${explorer.src.dir}\src"/>
				<pathelement location="${common.src.dir}"/>
				<pathelement location="${dlc}\gui"/>
				<pathelement location="${dlc}\gui\adecomm.pl"/>
				<pathelement location="${dlc}\gui\adecomp.pl"/>
				<pathelement location="${dlc}\gui\adedict.pl"/>
				<pathelement location="${dlc}\gui\adeedit.pl"/>
				<pathelement location="${dlc}\gui\adeicon.pl"/>
				<pathelement location="${dlc}\gui\adeshar.pl"/>
				<pathelement location="${dlc}\gui\adeuib.pl"/>
				<pathelement location="${dlc}\gui\adeweb.pl"/>
				<pathelement location="${dlc}\gui\adexml.pl"/>
				<pathelement location="${dlc}\gui\dataadmin.pl"/>
				<pathelement location="${dlc}\gui\prodict.pl"/>
				<pathelement location="${dlc}\gui\protools.pl"/>
				<pathelement location="${dlc}\gui\OpenEdge.Core.pl"/>
				<pathelement location="${dlc}\gui\OpenEdge.BusinessLogic.pl"/>
				<pathelement location="${dlc}\gui\netlib\OpenEdge.Net.pl"/>
				<pathelement location="${dlc}"/>
				<pathelement location="${dlc}\bin"/>
				<pathelement location="${dlc}\src"/>
			</propath>
		</PCTCompile>
```

**Comment by gquerret** [comment] 2021-02-18 08:29
This comes from the multithreaded compiler, I now also have the error message. But I end up with a socket error which at least fails the build. In both cases, this is not the expected behavior, I'll fix that.

**Comment by gquerret** [comment] 2021-02-18 09:04
This comes from how the warning `TRANSACTION keyword given within actual transaction level. (214)` is handled. This specific message contains unknown values in its description, and that's incorrectly handled by the code sending information back to the Java process.
Fix will come soon.

**Comment by gquerret** [comment] 2021-02-18 16:00
This branch contains the fix: https://ci.rssw.eu/job/PCT/job/bugfix%252FPCT-443/9/
Can you try it before I merge it in the main branch ?

**Comment by alexwiese** [comment] 2021-02-18 22:27
@gquerret thanks for the quick response and fix. 

I just tested it and it correctly fails as expected. All looks OK.

**Comment by gquerret** [comment] 2021-02-19 06:56
Merged in master. Release will happen later, the issue is less critical than I thought it was at the beginning.

**Closed as completed by gquerret** 2021-02-19 06:56 UTC
