### ISSUE TITLE
PCTLoadSchema does not fail if the database is locked.

### ISSUE THREAD

**Issue by djbrown92** [Riverside-Software/pct#117] opened 2015-10-15 15:58 UTC
If I have an application session running against the database whilst the PCTLoadSchema is running, in the console output I see the message, "[PCTLoadSchema] Lock wait timeout of 1800 seconds expired". In my Jenkins Job I test for the ERRORLEVEL and wish to take action if the load schema fails but I'm finding that the ERRORLEVEL remains set to 0 despite the "Lock wait timeout" message. Any suggestions please?

**Comment by jakejustus** [comment] 2015-10-15 19:17
Switched comment from title to body !
 If I have an application session running against the database whilst the PCTLoadSchema is running, in the console output I see the message, "[PCTLoadSchema] Lock wait timeout of 1800 seconds expired". In my Jenkins Job I test for the ERRORLEVEL and wish to take action if the load schema fails but I'm finding that the ERRORLEVEL remains set to 0 despite the "Lock wait timeout" message. Any suggestions please?

**Comment by jakejustus** [comment] 2015-10-15 19:18
Please provide PCT Version number as well as OE Version. PCTLoadSchema behavior is different since 11.3

**Comment by djbrown92** [comment] 2015-10-15 19:56
Thanks, Gilles. It's OE10.2B and Ant 1.2. I'll check the version of PCT tomorrow.

**Comment by djbrown92** [comment] 2015-10-16 09:29
Version details now added:

[PCTVersion] PCT Version 0.19-pre - Build 162
     [echo] OpenEdge Release 10.2B06 as of Mon Mar 19 19:14:30 EDT 2012 as of  Mon Mar 19 19:14:30 EDT 2012

**Comment by jakejustus** [comment] 2015-10-16 09:55
Thanks, will have a look.

**Comment by jakejustus** [comment] 2015-10-18 08:29
Hi,

Only tested for now on 11.5 with the latest version of PCT, and timeout is correctly trapped. At least, you can upgrade :-)
I'll reproduce on 10.2B, but I know that error trapping is quite difficult in 10.2B version of dictionary load.

**Comment by jakejustus** [comment] 2015-10-18 11:02
I confirm the problem is there in 10.2B. However, the message returned by OpenEdge is not really an error message, so it's not caught by the load schema procedure. Given the time it will take to have fix the problem (without breaking everything else) and that 10.2B is not exactly a recent version, that won't be fixed directly in PCT trunk.

**Closed as completed** 2015-10-18 11:03 UTC

**Comment by djbrown92** [comment] 2015-10-19 09:16
Ok. Thanks for your efforts and responses on this.
