### ISSUE TITLE
Error when using PCTDumpIncremental to generate incremental for a TDE database

### ISSUE THREAD

**Issue by Daniel-S-B** [Riverside-Software/pct#366] opened 2019-06-06 13:43 UTC
### Subject of the issue
I can't generate the incremental .df using PCTDumpIncremental on TDE database, no error message is displayed in ANT log but it stops due to return code 1.

### Your environment
* Win 10
* OpenEdge 11.7
* Ant 1.10.5
* PCT 211

### Actual behaviour
When the database is TDE encrypted and create incremental df using PCTDumpIncremental task return code 1 error is logged and build failed. No error message is displayed. 

### Expected behaviour
I expected to have the warning captured in 'incrdump.e' file and dump file created.

### Steps to reproduce
Use PCTDumpIncremental to generate the incremental DF between the two TDE databases.

**Comment by gquerret** [comment] 2019-06-07 06:46
I confirm that this has never been tested. I'll have a look.

**Comment by gquerret** [comment] 2019-06-18 16:53
I've reproduced the problem, PCTDumpIncremental returns a build failure but without any meaningful message. No ETA for a fix, contact me offline if you want it fixed quickly.

**Comment by gquerret** [comment] 2023-02-06 07:06
Seems to be related to missing `ROUTINE-LEVEL ON ERROR UNDO, THROW` in the call stack. I need to double check, that's not entirely clear.

**Comment by gquerret** [comment] 2023-02-10 15:36
Merged in `main`. Changed error handling mechanism in PCTDynamicRun.

**Closed as completed by gquerret** 2023-02-10 15:36 UTC
Labels: bug
