### ISSUE TITLE
HTMLDocumentation task error on class with LIKE temp-table definition 

### ISSUE THREAD

**Issue by Mazenrab** [Riverside-Software/pct#289] opened 2018-02-26 16:09 UTC
### Subject of the issue
I have an error when i'm use HTMLDocumentation task on class which contains LIKE temp-table definition.
If I remove such classes (using temp-table like definition) HTMLDocumentation works fine.

### Your environment
Windows 7 Enterprise SP1 64-bit
OpenEdge Release 11.6.3 as of Thu Sep  8 19:01:50 EDT 2016
Use default OE 11.6.3 Ant 
PCT Version : pct-208-master-87b954be01663bf64f7b435edb02afdd6b4044fa

### Actual behaviour
```
[HTMLDocumentation] Generating HTML documentation for C:\...\dd
[HTMLDocumentation] An Consultingwerk.Exceptions.Exception has occured:
[HTMLDocumentation] The buffer eTempTable has no field named like.
[HTMLDocumentation] C:\Users\PAKHNY~1\AppData\Local\Temp\pctinit10275.p at line 31  (C:\Users\PAKHNY~1\AppData\Local\Temp\pctinit10275.p)
[HTMLDocumentation] Consultingwerk/Studio/ClassDocumentation/generate-class-reference.p at line 139  (Consultingwerk/Studio/ClassDocumentation/generate-class-reference.r)
[HTMLDocumentation] ClassRelationProvider Consultingwerk.Studio.ClassDocumentation.ClassRelationProvider at line 638  (Consultingwerk/Studio/ClassDocumentation/ClassRelationProvider.r)
[HTMLDocumentation] ParseClassDocumentation Consultingwerk.Studio.ClassDocumentation.ClassDocumentationParser at line 619  (Consultingwerk/Studio/ClassDocumentation/ClassDocumentationParser.r)
[HTMLDocumentation] StartElement Consultingwerk/sax-reader-handler.p at line 94  (Consultingwerk/sax-reader-handler.r)
[HTMLDocumentation] SaxStartElement Consultingwerk.Studio.ClassDocumentation.ClassDocumentationParser at line 821  (Consultingwerk/Studio/ClassDocumentation/ClassDocumentationParser.r)
[HTMLDocumentation] ParseSaxAttributesToBuffer Consultingwerk.Util.BufferHelper at line 218  (Consultingwerk/Util/BufferHelper.r)
[HTMLDocumentation] HasField Consultingwerk.Assertion.BufferAssert at line 64  (Consultingwerk/Assertion/BufferAssert.r)

BUILD FAILED
C:\...\build.xml:42: Return code : 1

```
### Steps to reproduce
It looks like the problem appears when using temp-table definition **only** with LIKE in the CLASS.
I created simple class to reproduce that (i'm using table e-mails from my DB).

```
USING Progress.Lang.*.

BLOCK-LEVEL ON ERROR UNDO, THROW.

CLASS rt.Domain.test.test:

define private temp-table tt-e-mails no-undo like e-mails.
define private dataset dsEmail for tt-e-mails.

END CLASS.
```
XML:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<unit packageName="rt.Domain.test" className="test" isAbstract="false" isFinal="false" isInterface="false" isEnum="false" isSerializable="false" useWidgetPool="false">
    <using name="Progress.Lang.*" type="NONE"/>
    <temp-table name="tt-e-mails" like="e-mails" definition="" noUndo="true">
        <text>DEFINE TEMP-TABLE tt-e-mails LIKE e-mails NO-UNDO 
</text>
    </temp-table>
</unit>

```

**Comment by gquerret** [comment] 2018-02-26 16:27
Duplicate of #251 
You can use this [pre-release](https://github.com/Riverside-Software/pct/releases/tag/v209-pre2) if you want to test it, or build PCT by yourself.

**Closed as completed by gquerret** 2018-02-26 16:27 UTC

**Comment by Mazenrab** [comment] 2018-02-26 16:57
Thanks, it's work.
